[package]
name = "treshold-min"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = { version = "0.3.31", default-features = false }
genawaiter-try = { git = "https://github.com/parrrate/genawaiter-try.git", version = "0.1.0" }
